### ISSUE TITLE
Mismatch RecognitionStatus value when long-form dictation ends

### ISSUE THREAD

**Issue by boxfish** [Microsoft/Cognitive-Speech-STT-iOS#12]
In long-form dictation mode, the SDK expect the service to return RecognitionStatus_EndOfDictation (612) when it reaches the 2 mins limit, but currently the service returns 611 instead.

**Comment by jasonvomsft** [comment]
Error 611 was missed in the latest SDK drop.  This error code means you have reached the upper limit.
