### ISSUE TITLE
Universal Framework

### ISSUE THREAD

**Issue by tbass134** [Microsoft/Cognitive-Speech-STT-iOS#17]
Is is possible to combine both the device framework of the SpeechSDK with the simulator version of the SDK into one Universal Framework. Having two separate frameworks that must be swapped in order to run on either the device or the simulator is a real pain.
Can this be done using lipo?

**Comment by shun-sato93** [comment]
I wrote a shell script for combining device and simulator version of framework.
[integrate.sh.zip](https://github.com/Microsoft/Cognitive-Speech-STT-iOS/files/587306/integrate.sh.zip)

Usage:
Place each frameworks like a screenshot below and run script
$./integrate.sh

![screen shot 2016-11-13 at 1 12 00 am](https://cloud.githubusercontent.com/assets/18710786/20239199/86eb93b6-a93e-11e6-9d73-3e7a3636e4e3.png)

**Comment by tbass134** [comment]
@shun-sato93  thank you! These frameworks do not include the swift module, so i just removed that portion of the script and it builds on both device and sim
