### ISSUE TITLE
Is there a way to configure microphone timeout?

### ISSUE THREAD

**Issue by gearoidoceallaigh** [Microsoft/Cognitive-Speech-STT-iOS#20]
I see that `SpeechRecognitionService` has a `MicrophoneTimeout` but can you tell me how (if possible) I can configure it?

Thanks!

**Comment by priyaravi20** [comment]
THis is not a configurable parameter. There are parameters part of recognition status that can be used to figure if service has endpointed so you can stop it from client side.
