### ISSUE TITLE
Source code for SDK?

### ISSUE THREAD

**Issue by joshuawarner32** [Microsoft/Cognitive-Speech-STT-iOS#3]
Would it be possible to get the source code for this SDK, rather than just binaries?

It's a lot easier to trust that nothing nefarious is going on if I can glance through the source.  Also, it's a lot easier to adapt the SDK to a platform it wasn't originally built for (in my case, a linux server).

**Comment by srozga** [comment]
I would also find it useful to have the source. I am experimenting with adding Xamarin bindings on top of this SDK but Xamarin only supports statically linked libraries. It seems that the SpeechSDK is currently dynamic framework so I cannot use it in my Xamarin app. I am able to use the REST API to get speech recognition, but I would like support for partial results.

**Comment by jasonvomsft** [comment]
Hello @srozga, @joshuawarner32 We will not be providing source code for the Speech SDKs at this time.
