### ISSUE TITLE
MicrophoneRecognitionClient stops working after onError callback

### ISSUE THREAD

**Issue by phongcao** [Microsoft/Cognitive-Speech-STT-iOS#4]
**Repro Steps:**
1. Press start button.
2. Quickly switch the airplane mode on and off in order to simulate the network connection drops.
3. onError callback returns: "_Transport error Unknown error: -2147418113_".
4. Press start button again.
5. The app stops working with error: "_SpeechClientStatus_MicrophoneInUse_".

When this issue happens, it doesn't help even if I try to stop the recognition using endMicAndRecognition method or re-initialize the MicrophoneRecognitionClient. The only way is to reset the app.

**Comment by Quij** [comment]
This has been happening to me too. Though in my case, it was while running the app with a simulated poor connection.

On an iPhone:
1. Settings > Developer > Network Link Conditioner Status > Enable > Very Bad Network.
2. Launch SpeechRecognitionServerExample.
3. Press start button.
4. onError callback returns: "_Transport error Unknown error: -2147418113_".
5. Press start button again.
6. The app stops working with error: "_SpeechClientStatus_MicrophoneInUse_".

After getting the _SpeechClientStatus_MicrophoneInUse_ status, any subsequent calls to endMicAndRecognition never return (the app just hangs).

**Comment by jasonvomsft** [comment]
Can you verify if the latest SDK has addressed the issue?

**Comment by phongcao** [comment]
It seems to work great now. Thanks!
