### ISSUE TITLE
what should i do if i want to change the language to be recognized

### ISSUE THREAD

**Issue by xsywayne11** [Microsoft/Cognitive-Speech-STT-iOS#6]
need i to call the method +(MicrophoneRecognitionClient*)createMicrophoneClient:(SpeechRecognitionMode)speechRecognitionMode
                                         withLanguage:(NSString*)language
                                       withPrimaryKey:(NSString*)primaryKey
                                     withSecondaryKey:(NSString*)secondaryKey
                                         withProtocol:(id<SpeechRecognitionProtocol>)delegate; ????

**Comment by jasonvomsft** [comment]
Yes, that's the correct API to use.  You'll want to change the 'withLanguage' argument.
