### ISSUE TITLE
Transport error SpeechClentStatus_LoginFaild

### ISSUE THREAD

**Issue by sohilmultani** [Microsoft/Cognitive-Speech-STT-iOS#9]
i have create project to translate Speech to text.
So i have download this demo and use it but it will give me error : 
"Transport error SpeechClentStatus_LoginFaild"

I have subscrive : " Speaker Recognition - Preview " in above Link
https://www.microsoft.com/cognitive-services/en-us/subscriptions

i have give Two Keys - key1 and key2
i have set key1 in setting.plist file and execute this demo - "Use Microphone with ShortPhrase mode"
but it will give me Error : "Transport error SpeechClentStatus_LoginFaild"

also i have set Key2 in setting.plist file and execute this demo - "Use Microphone with ShortPhrase mode"
but it will give me Error : "Transport error SpeechClentStatus_LoginFaild"

i have confused what is the "luisSubscriptionID" and "luisAppID" ?

i am not set "luisSubscriptionID" and "luisAppID" if i am any Mistake please give me suggestion.

I have give this in Log ERROR : 

Microphone permissions: 0
WebSocket closed unexpectedly, status: 0
Closing web socket channel
CU Client connection dropped
ConnectionStateChanged
Upgrade request returned with HTTP status code: 403.
Web socket handshake failed, hr=8E200002
web socket message delivery failed, hr=8E200002
Web socket channel already closed.
Message: 'connection.context' has 4 remaining transmit attempts.
Retrying message, name='connection.context'
Initiating websocket connection. m_connection=0x156bfb5c host=websockets.platform.bing.com port=443
Auth token status: 401
originating error 0x8000ffff
originating error 0x80070057
Authorization token hr 80070057 '' 
Refreshing token /sts/v1.0/issueToken
WSRequest

WebSocket closed unexpectedly, status: 0

Please Help Me.

**Comment by jasonvomsft** [comment]
Is this still occurring?

**Comment by priyaravi20** [comment]
LUIS ids are not needed for doing Use Microphone with ShortPhrase mode. You can use either Key 1 or 2 for doing the recognition.

**Comment by ShubamGupta09** [comment]
I have done the same but i am getting the same please help me @priyaravi20

**Comment by ShubamGupta09** [comment]
Microphone permissions: 0
originating error 0x8e200005
originating error 0x8e200005
WebSocket closed unexpectedly, status: 0
Closing web socket channel
Web socket channel closed (state = 0)
CU Client connection dropped
ConnectionStateChanged
Web socket handshake failed, hr=8E200005
web socket message delivery failed, hr=8E200005
Web socket channel already closed.
Message: 'connection.context' has 3 remaining transmit attempts.
Retrying message, name='connection.context'
Initiating websocket connection. m_connection=0x102289458 host=websockets.platform.bing.com port=443
originating error 0x8e200005
originating error 0x8e200005
originating error 0x80070057
Authorization token hr 80070057 '' 
Refreshing token /sts/v1.0/issueToken
WSRequest
